### ISSUE TITLE
Hello, there is a user impersonating you

### ISSUE THREAD

**Issue by operator-id** [jstortoise/test_problems#11]
Hello, there is a user impersonating u on LinkedIn and other personal sites where he linked this git page. He claims to be from South Korea, did studies in Honk Kong and now lives in New York. He tries to convince various ppl into scams.

Can you please let me now that you are a different person? (Or maybe he is not a fraud and I am  wrong :) )

**Comment by jstortoise** [comment]
@operator-id , thanks for your contact. Can you please send me his/her linkedin profile?

**Comment by operator-id** [comment]
https://www.linkedin.com/in/leonardolong/
This guy, I found the git link on his linked personal website
"leonardolong.com" I guess, check his LinkedIn

**Comment by jstortoise** [comment]
It's not me but he's not a fraud too. I'll close this issue.
